version: '3.8'
services:
  simple-memory-server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    command: sleep infinity
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5135
    ports:
      - "5135:5135"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
